# Workflow to automatically create the godot openxr loaders addon
name: Build on push

on: [push]

env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/

jobs:
  build:
    name: Building for ${{ matrix.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: 🐧 Linux (x86_64, GCC)
            os: ubuntu-22.04
            platform: linux
            flags: arch=x86_64
            artifact_name: build-files-linux-x86_64
            artifact_path: aar/demo/addons/godotopenxrvendors/.bin/linux/*/*/*.so
            cache-name: linux-x86_64
          # Not sure how to cross compile these
          # - name: Linux (arm64)
          #   os: ubuntu-22.04
          #   platform: linux
          #   flags: arch=arm64
          #   artifact_name: build-files-linux-arm64
          #   artifact_path: aar/demo/addons/godotopenxrvendors/.bin/linux/*/*/*.so
          #   cache-name: linux-arm64
          # - name: Linux (rv64)
          #  os: ubuntu-22.04
          #  platform: linux
          #  flags: arch=rv64
          #  artifact_name: build-files-linux-rv64
          #  artifact_path: aar/demo/addons/godotopenxrvendors/.bin/linux/*/*/*.so
          #  cache-name: linux-rv64
          - name: 🏁 Windows (x86_64, MSVC)
            os: windows-latest
            platform: windows
            artifact_name: build-files-windows
            artifact_path: aar/demo/addons/godotopenxrvendors/.bin/windows/*/*/*.dll
            cache-name: windows-x86_64-msvc
          - name: 🍎 MacOS (universal)
            os: macos-latest
            platform: macos
            flags: arch=universal
            artifact_name: build-files-macos
            artifact_path: aar/demo/addons/godotopenxrvendors/.bin/macos/*/*.framework
            cache-name: macos-universal
          - name: 🤖 Android (arm64)
            os: ubuntu-22.04
            platform: android
            flags: arch=arm64
            artifact_name: build-files-android-arm64
            artifact_path: |
              aar/plugin/src/main/libs/*/*/*/*.so
            cache-name: android-arm64
          - name: 🤖 Android (x86_64)
            os: ubuntu-22.04
            platform: android
            flags: arch=x86_64
            artifact_name: build-files-android-x86_64
            artifact_path: |
              aar/plugin/src/main/libs/*/*/*/*.so
            cache-name: android-x86_64


    # Note, to satisfy the asset library we need to make sure our zip files have a root folder
    # this is why we checkout into aar and build into asset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: aar
          submodules: recursive
      - name: Restore Godot build cache
        uses: ./aar/thirdparty/godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true
      - name: Set up Python (for SCons)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Android dependencies
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          link-to-sdk: true
        if: matrix.platform == 'android'
      - name: Install scons
        run: |
          python -m pip install scons==4.0.0
      - name: Create extension library
        run: |
          cd aar
          scons platform=${{ matrix.platform }} target=template_debug ${{ matrix.flags }} custom_api_file=thirdparty/godot_cpp_gdextension_api/extension_api.json build_profile=thirdparty/godot_cpp_build_profile/build_profile.json
          scons platform=${{ matrix.platform }} target=template_release ${{ matrix.flags }} custom_api_file=thirdparty/godot_cpp_gdextension_api/extension_api.json build_profile=thirdparty/godot_cpp_build_profile/build_profile.json
          cd ..
      - name: Save Godot build cache
        uses: ./aar/thirdparty/godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true
      - name: Upload build files (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_path }}

  asset:
    name: Assembling the asset
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: aar
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Copy Android binaries
        run: |
          mkdir aar/plugin/src/main/libs
          cp -r build-files-android-arm64/* aar/plugin/src/main/libs/
          cp -r build-files-android-x86_64/* aar/plugin/src/main/libs/
      - name: Create Godot OpenXR Vendors AARs
        run: |
          cd aar
          ./gradlew build
          cd ..
      - name: Create Godot OpenXR Vendors Addon
        run: |
          mkdir asset
          cp -r aar/demo/addons asset
          cp aar/CHANGES.md asset/addons/godotopenxrvendors/GodotOpenXRVendors_CHANGES.md
      - name: Adding vendor licences
        run: |
          mkdir -p asset/addons/godotopenxrvendors/meta/
          cp aar/thirdparty/khronos_openxr_sdk/LICENSE asset/addons/godotopenxrvendors/meta/LICENSE

          mkdir -p asset/addons/godotopenxrvendors/pico/
          cp aar/thirdparty/khronos_openxr_sdk/LICENSE asset/addons/godotopenxrvendors/pico/LICENSE

          mkdir -p asset/addons/godotopenxrvendors/khronos/
          cp aar/thirdparty/khronos_openxr_sdk/LICENSE asset/addons/godotopenxrvendors/khronos/LICENSE

          mkdir -p asset/addons/godotopenxrvendors/magicleap/
          cp aar/thirdparty/khronos_openxr_sdk/LICENSE asset/addons/godotopenxrvendors/magicleap/LICENSE

      - name: Copying artifacts
        run: |
          mkdir -p asset/addons/godotopenxrvendors/.bin/android/template_debug/arm64
          mkdir -p asset/addons/godotopenxrvendors/.bin/android/template_release/arm64
          cp -r build-files-android-arm64/debug/*/*/*.so asset/addons/godotopenxrvendors/.bin/android/template_debug/arm64/
          cp -r build-files-android-arm64/release/*/*/*.so asset/addons/godotopenxrvendors/.bin/android/template_release/arm64/

          mkdir -p asset/addons/godotopenxrvendors/.bin/android/template_debug/x86_64
          mkdir -p asset/addons/godotopenxrvendors/.bin/android/template_release/x86_64
          cp -r build-files-android-x86_64/debug/*/*/*.so asset/addons/godotopenxrvendors/.bin/android/template_debug/x86_64/
          cp -r build-files-android-x86_64/release/*/*/*.so asset/addons/godotopenxrvendors/.bin/android/template_release/x86_64/

          mkdir -p asset/addons/godotopenxrvendors/.bin/linux/
          cp -r build-files-linux-x86_64/* asset/addons/godotopenxrvendors/.bin/linux/

          mkdir -p asset/addons/godotopenxrvendors/.bin/windows/
          cp -r build-files-windows/* asset/addons/godotopenxrvendors/.bin/windows/

          mkdir -p asset/addons/godotopenxrvendors/.bin/macos/
          cp -r build-files-macos/* asset/addons/godotopenxrvendors/.bin/macos/

      - name: Create Godot OpenXR Vendor addon artifact
        uses: actions/upload-artifact@v4
        with:
          name: GodotOpenXRVendorsAddon
          include-hidden-files: true
          path: |
            asset
      - name: Zip addon
        run: |
          zip -qq -r godotopenxrvendorsaddon.zip asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      - name: Create and upload asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "godotopenxrvendorsaddon.zip"
          draft: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pushhing' && startsWith(github.ref, 'refs/tags')

  run_xr_simulator:
   name: "Run XR Simulator"
   #runs-on: windows-latest
   runs-on: macos-latest
   needs: build

   env:
     GODOT_VERSION: "4.4.1-stable"
     XRSIM_VERSION: "65.0.0"

   steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: 'true'
          
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          # You can set the Vulkan SDK version to download.
          # Defaults to latest version, if version not set.
          #vulkan_version: 1.3.231.2
          optional_components: com.lunarg.vulkan.vma,com.lunarg.vulkan.sdl2,com.lunarg.vulkan.glm,com.lunarg.vulkan.volk
          #,com.lunarg.vulkan.32bit,com.lunarg.vulkan.debug32,com.lunarg.vulkan.thirdparty,com.lunarg.vulkan.debug
          install_runtime: true
          cache: true
          stripdown: true

          # You can install a software rasterizer.
          install_swiftshader: true
          install_lavapipe: true
          
      - name: Install 7zip
        run: |
          brew update -y
          brew install 7zip tree -y

      - name: Download Godot
        run: |
          curl -o godot.zip -L "https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}_macos.universal.zip"

      - name: Extract Godot
        run: |
          unzip "godot.zip"
          tree

      #- name: Download SwiftShader vulkan-1.dll
      #  run: |
      #    Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/r6radx6b125555xkxue20/vulkan-1.dll?rlkey=ffv3cgvqbytivm1zy119hss7n&st=frcettrf&dl=1" -OutFile "vulkan-1.dll"

      - name: Download Meta XR Simulator
        run: |
          brew tap Oculus-VR/tap
          brew install meta-xr-simulator
          sudo /opt/homebrew/Cellar/meta-xr-simulator/__VERSION__/post_installation_macos.sh
          brew info meta-xr-simulator

      - name: Download macos build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files-macos
          path: build-files-macos

      - name: Copy Windows build of the addon into the demo and samples project
        run: |
          mkdir -p demo/addons/godotopenxrvendors/.bin/macos/
          cp -r build-files-macos/* demo/addons/godotopenxrvendors/.bin/macos/

          for project in samples/*/; do
            cp -r demo/addons "$project"
          done

      - name: Import the demo and sample projects
        run: |
          godot="Godot_v${GODOT_VERSION}_macos.universal"
          echo ""
          echo " ** Importing demo project"
          echo ""

          "$godot" --path demo --import --headless

          for project in samples/*/; do
            project_file="${project}project.godot"
            if [ -f "$project_file" ]; then
              echo ""
              echo " ** Importing project $(basename "$project")"
              echo ""
              "$godot" --path "$project" --import --headless
            fi
          done

      - name: Launch a synthetic environment
        run: |
          # Ensure a synthetic environment isn't already running.
          /opt/homebrew/Cellar/meta-xr-simulator/__VERSION__/synth_env_server/LaunchLivingRoom.sh

      - name: Run tests
        run: |
          
          jsonPath="$HOME/Library/Application Support/MetaXR/MetaXrSimulator/persistent_data.json"

          # Find .vrs files in demo/tests and samples/*/tests directories.
          demoVrsFiles=( $(find demo/tests -type f -name "*.vrs") )
          sampleVrsFiles=( $(find samples -type f -path "*/tests/*.vrs") )
          # Combine both arrays into one.
          vrsFiles=( "${demoVrsFiles[@]}" "${sampleVrsFiles[@]}" )

          for file in "${vrsFiles[@]}"; do
            # Compute the replay file path by appending '-replay' to the base name.
            dir=$(dirname "$file")
            base=$(basename "$file" .vrs)
            replayPath="${dir}/${base}-replay.vrs"
  
            # Construct the JSON content.
            jsonContent=$(cat <<EOF
          {
            "session_capture": {
              "delay_start_ms": 5000,
              "exec_state": "replay",
              "quit_buffer_ms": 5000,
              "quit_when_complete": true,
              "record_path": "$(readlink -f "$file")",
              "replay_path": "$(readlink -f "$replayPath")"
            }
          }
          EOF
          )
            # Create the directory for the JSON file, then write the content.
            mkdir -p "$(dirname "$jsonPath")"
            echo "$jsonContent" > "$jsonPath"
            echo "$jsonContent"
  
            # Define the Godot executable.
            # Adjust the executable name as needed. For Linux you might have something like:
            #   godot="Godot_v${GODOT_VERSION}_linux.x86_64"
            # Here we assume the naming is similar to the given one.
            godot="Godot_v${GODOT_VERSION}_macos.universal"
  
            timeout=300
            waitTime=0

            # Determine the project path which is the parent directory of the .vrs file's directory.
            projectPath=$(dirname "$(dirname "$file")")

            echo ""
            echo " ** Running VRS $(basename "$file") on $(basename "$projectPath") project"
            echo ""

            # Start the Godot process in background.
            "$godot" --path "$projectPath" --rendering-method mobile --verbose -- --xrsim-automated-tests &
            pid=$!

            # Wait for the process to complete, but with a timeout.
            while kill -0 "$pid" 2>/dev/null && [ $waitTime -lt $timeout ]; do
              sleep 1
              waitTime=$((waitTime+1))
            done

            if kill -0 "$pid" 2>/dev/null; then
              echo "Process is still running after $timeout seconds. Stopping the process."
              kill "$pid"
              exit 1
            else
              echo "Process completed within $waitTime seconds."
            fi

            # Check that the replay file was generated.
            if [ ! -f "$replayPath" ]; then
              echo "Replay file not found: $replayPath" >&2
              exit 1
            fi
          done

      - name: Stop synthetic environment
        run: |
          pkill synth_env_server

      - name: Upload VRS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ReplayVRS
          path: |
            test-scripts/
            **/*/tests/*.vrs

  compare_vrs_replay:
    name: "Compare VRS replay"
    runs-on: ubuntu-latest
    needs: run_xr_simulator

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download VRS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ReplayVRS
          path: tests/vrs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/vrs_pixmatch/requirements.txt

      - name: Compare VRS replay with expected recordings
        run: |
          cd tests/vrs/

          mkdir diffs
          for replay in $(find . -name \*-replay.vrs); do
            echo " ==> Checking $replay..."
            expected=$(echo $replay | sed -e 's/-replay.vrs$/.vrs/')
            diff_path="diffs/$replay"
            mkdir -p "$diff_path"
            python ../../scripts/vrs_pixmatch/vrs_pixmatch.py "$expected" "$replay" --threshold 0.4 --max-pixel-diff 40000 --output-path "$diff_path" --verbose
          done

      - name: Upload VRS diff artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ReplayVRSDiff
          path: tests/vrs/diffs/**/*
